# Generated by Django 5.1.2 on 2024-10-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
    ]
